# TCL File Generated by Component Editor 15.1
# Thu May 19 23:56:13 PDT 2016
# DO NOT MODIFY


# 
# mda_adc_wrapper "mda_adc" v1.0
#  2016.05.19.23:56:13
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module mda_adc_wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME mda_adc_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mda_adc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mda_adc_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mda_adc.v VERILOG PATH mda_adc.v
add_fileset_file mda_adc_controller.v VERILOG PATH mda_adc_controller.v
add_fileset_file mda_adc_wrapper.v VERILOG PATH mda_adc_wrapper.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink slave_reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink_adc
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ADC_CONVST convst_out Output 1
add_interface_port conduit_end ADC_SCK sck_out Output 1
add_interface_port conduit_end ADC_SDI sdi_out Output 1
add_interface_port conduit_end ADC_SDO sdo_in Input 1


# 
# connection point adc_slave
# 
add_interface adc_slave avalon end
set_interface_property adc_slave addressUnits WORDS
set_interface_property adc_slave associatedClock clock_sink
set_interface_property adc_slave associatedReset reset_sink
set_interface_property adc_slave bitsPerSymbol 8
set_interface_property adc_slave burstOnBurstBoundariesOnly false
set_interface_property adc_slave burstcountUnits WORDS
set_interface_property adc_slave explicitAddressSpan 0
set_interface_property adc_slave holdTime 0
set_interface_property adc_slave linewrapBursts false
set_interface_property adc_slave maximumPendingReadTransactions 0
set_interface_property adc_slave maximumPendingWriteTransactions 0
set_interface_property adc_slave readLatency 0
set_interface_property adc_slave readWaitTime 1
set_interface_property adc_slave setupTime 0
set_interface_property adc_slave timingUnits Cycles
set_interface_property adc_slave writeWaitTime 0
set_interface_property adc_slave ENABLED true
set_interface_property adc_slave EXPORT_OF ""
set_interface_property adc_slave PORT_NAME_MAP ""
set_interface_property adc_slave CMSIS_SVD_VARIABLES ""
set_interface_property adc_slave SVD_ADDRESS_GROUP ""

add_interface_port adc_slave chipselect_n chipselect_n Input 1
add_interface_port adc_slave addr address Input 1
add_interface_port adc_slave read_n read_n Input 1
add_interface_port adc_slave readdata readdata Output 32
add_interface_port adc_slave write_n write_n Input 1
add_interface_port adc_slave writedata writedata Input 32
set_interface_assignment adc_slave embeddedsw.configuration.isFlash 0
set_interface_assignment adc_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment adc_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment adc_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink_adc
# 
add_interface clock_sink_adc clock end
set_interface_property clock_sink_adc clockRate 0
set_interface_property clock_sink_adc ENABLED true
set_interface_property clock_sink_adc EXPORT_OF ""
set_interface_property clock_sink_adc PORT_NAME_MAP ""
set_interface_property clock_sink_adc CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_adc SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_adc adc_clk clk Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink slave_clk clk Input 1

