# TCL File Generated by Component Editor 15.1
# Sun May 15 01:33:38 PDT 2016
# DO NOT MODIFY


# 
# RS232 "RS232" v1.0
#  2016.05.15.01:33:38
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module RS232
# 
set_module_property DESCRIPTION ""
set_module_property NAME RS232
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME RS232
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Altera_UP_Avalon_RS232
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Altera_UP_Avalon_RS232.v VERILOG PATH Altera_UP_Avalon_RS232.v TOP_LEVEL_FILE
add_fileset_file Altera_UP_RS232_Counters.v VERILOG PATH Altera_UP_RS232_Counters.v
add_fileset_file Altera_UP_RS232_In_Deserializer.v VERILOG PATH Altera_UP_RS232_In_Deserializer.v
add_fileset_file Altera_UP_RS232_Out_Serializer.v VERILOG PATH Altera_UP_RS232_Out_Serializer.v
add_fileset_file Altera_UP_SYNC_FIFO.v VERILOG PATH Altera_UP_SYNC_FIFO.v


# 
# parameters
# 
add_parameter BAUD_COUNTER_WIDTH INTEGER 9
set_parameter_property BAUD_COUNTER_WIDTH DEFAULT_VALUE 9
set_parameter_property BAUD_COUNTER_WIDTH DISPLAY_NAME BAUD_COUNTER_WIDTH
set_parameter_property BAUD_COUNTER_WIDTH TYPE INTEGER
set_parameter_property BAUD_COUNTER_WIDTH UNITS None
set_parameter_property BAUD_COUNTER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BAUD_COUNTER_WIDTH HDL_PARAMETER true
add_parameter BAUD_TICK_INCREMENT STD_LOGIC_VECTOR 1
set_parameter_property BAUD_TICK_INCREMENT DEFAULT_VALUE 1
set_parameter_property BAUD_TICK_INCREMENT DISPLAY_NAME BAUD_TICK_INCREMENT
set_parameter_property BAUD_TICK_INCREMENT TYPE STD_LOGIC_VECTOR
set_parameter_property BAUD_TICK_INCREMENT UNITS None
set_parameter_property BAUD_TICK_INCREMENT ALLOWED_RANGES 0:1023
set_parameter_property BAUD_TICK_INCREMENT HDL_PARAMETER true
add_parameter BAUD_TICK_COUNT STD_LOGIC_VECTOR 433
set_parameter_property BAUD_TICK_COUNT DEFAULT_VALUE 433
set_parameter_property BAUD_TICK_COUNT DISPLAY_NAME BAUD_TICK_COUNT
set_parameter_property BAUD_TICK_COUNT TYPE STD_LOGIC_VECTOR
set_parameter_property BAUD_TICK_COUNT UNITS None
set_parameter_property BAUD_TICK_COUNT ALLOWED_RANGES 0:1023
set_parameter_property BAUD_TICK_COUNT HDL_PARAMETER true
add_parameter HALF_BAUD_TICK_COUNT STD_LOGIC_VECTOR 216
set_parameter_property HALF_BAUD_TICK_COUNT DEFAULT_VALUE 216
set_parameter_property HALF_BAUD_TICK_COUNT DISPLAY_NAME HALF_BAUD_TICK_COUNT
set_parameter_property HALF_BAUD_TICK_COUNT TYPE STD_LOGIC_VECTOR
set_parameter_property HALF_BAUD_TICK_COUNT UNITS None
set_parameter_property HALF_BAUD_TICK_COUNT ALLOWED_RANGES 0:1023
set_parameter_property HALF_BAUD_TICK_COUNT HDL_PARAMETER true
add_parameter TOTAL_DATA_WIDTH INTEGER 10
set_parameter_property TOTAL_DATA_WIDTH DEFAULT_VALUE 10
set_parameter_property TOTAL_DATA_WIDTH DISPLAY_NAME TOTAL_DATA_WIDTH
set_parameter_property TOTAL_DATA_WIDTH TYPE INTEGER
set_parameter_property TOTAL_DATA_WIDTH UNITS None
set_parameter_property TOTAL_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TOTAL_DATA_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ODD_PARITY STD_LOGIC_VECTOR 0
set_parameter_property ODD_PARITY DEFAULT_VALUE 0
set_parameter_property ODD_PARITY DISPLAY_NAME ODD_PARITY
set_parameter_property ODD_PARITY TYPE STD_LOGIC_VECTOR
set_parameter_property ODD_PARITY UNITS None
set_parameter_property ODD_PARITY ALLOWED_RANGES 0:3
set_parameter_property ODD_PARITY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 byteenable byteenable Input 4
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end UART_RXD uart_rxd_in Input 1
add_interface_port conduit_end UART_TXD uart_txd_out Output 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

